version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/module"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
